name: Deploy to Netlify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: bilingual-resume/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('bilingual-resume/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
        
    - name: Install dependencies
      working-directory: ./bilingual-resume
      run: npm ci
      
    - name: Build application
      working-directory: ./bilingual-resume
      run: npm run build
      env:
        NODE_ENV: production
        NEXT_PUBLIC_SITE_URL: https://negriniresume.netlify.app
        NEXT_PUBLIC_BUILD_TIME: ${{ github.event.head_commit.timestamp }}
        NEXT_PUBLIC_BUILD_ID: ${{ github.sha }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: bilingual-resume/out/
        retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: bilingual-resume/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('bilingual-resume/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
        
    - name: Install dependencies
      working-directory: ./bilingual-resume
      run: npm ci
      
    - name: Build for production
      working-directory: ./bilingual-resume
      run: npm run build
      env:
        NODE_ENV: production
        NEXT_PUBLIC_SITE_URL: https://negriniresume.netlify.app
        NEXT_PUBLIC_BUILD_TIME: ${{ github.event.head_commit.timestamp }}
        NEXT_PUBLIC_BUILD_ID: ${{ github.sha }}
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './bilingual-resume/out'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions - ${{ github.event.head_commit.message }}"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 10